<?php
/**
 * @file
 * Code for the wcspc_map feature.
 */

include_once 'wcspc_map.features.inc';

/**
 * Implements hook_boot().
 */
function wcspc_map_boot(){
  global $conf;
  $conf['locale_custom_strings_en'][''] = array(
    'Registration successful. You are now logged in.' => 'You just logged in (we\'ll email you some info about this site for future reference) now post a photo.'
  );
}

/**
 * Implements hook_node_submit().
 */
// Let's do this with a rules action instead
//function wcspc_map_node_submit(){
//  drupal_set_message(t('Your photo will be published as soon as our staff approves it.'));
//}

function wcspc_form_user_register_form_alter(&$form, $form_id) {
  drupal_set_title('You\'re one step from posting photos!');
  $form['field_demographic']['#weight'] = 2;
  dpm($form);
}
